version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    groups:
      bundler-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      bundler-security:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /vite
    schedule:
      interval: weekly
    groups:
      npm-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
